package:
  name: pyspotter
  version: 1

source:
  git_rev: 1
  git_url: https://github.com/javicarron/pyspotter.git

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy
    - astropy
    - scipy
    - wxpython
	- os
	- matplotlib
	- astroquery


test:
  imports:
    - pyspotter

about:
  home: https://github.com/javicarron/pyspotter
  license: GPL3
  license_file: LICENSE
  description: 'A small astronomical image viewer'
